version: "3.8"

services:

  db:
    container_name: "books-mysql"
    image: "mysql:5.7"
    ports: 
      - "3306:3306"
    volumes:
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
    restart: unless-stopped

  backend:
    container_name: "books-backend"
    depends_on: 
      - db
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: "books-backend:latest"
    ports:
      - "4000:4000"
    environment:
      SERVER_PORT: 4000
      DB_HOST: "books-mysql"
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_SCHEMA: books
    restart: unless-stopped
  
  nginx: 
    image: nginx:latest
    container_name: books-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./front-end/:/usr/share/nginx/html/
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped    
    